System:
  port: 9000


Appliances:
  - idname: tentLivingRight
    type: tent
    openPin: 24
    closePin: 23
    timeActionsSym: [1,3,5,10,15]
    fullyOpenTimeEst: 28
    fullyCloseTimeEst: 28

  - idname: tentLivingLeft
    type: tent
    openPin: 20
    closePin: 21
    timeActionsSym: [1,3,5,10,15]
    fullyOpenTimeEst: 28
    fullyCloseTimeEst: 28
  
